import { Kanit, Roboto } from 'next/font/google';
import Footer from '../components/layout/Footer';
import Header from '../components/layout/Header';
import './globals.css';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

const kanit = Kanit({
  variable: '--font-kanit',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${roboto.variable} ${kanit.variable} antialiased min-h-screen w-full relative bg-black text-white overflow-x-hidden`}>
        <div
          className='absolute inset-0 z-0'
          style={{
            background: `
        radial-gradient(ellipse 120% 70% at 70% 80%, rgba(87, 24, 69, 0.20), transparent 52%),
        radial-gradient(ellipse 160% 45% at 30% 30%, rgba(153, 27, 27, 0.16), transparent 58%),
        radial-gradient(ellipse 85% 100% at 10% 60%, rgba(69, 26, 3, 0.22), transparent 46%),
        #1c1917
      `,
          }}
        />

        <div className='relative z-10'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
