/**
 * Traces public/logo.png into a two-colour SVG so the wordmark can be themed with CSS
 * instead of shipping fixed-colour raster artwork. Re-runnable:
 *   node scripts/trace-logo.mjs
 * Replace this if the studio supplies a real vector original.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { join } from "node:path";

const src = join(process.cwd(), "public", "logo.png");
const out = join(process.cwd(), "public", "logo.svg");
const component = join(process.cwd(), "src", "components", "layout", "LogoMark.tsx");

function decodePng(buf) {
  let pos = 8;
  let width = 0;
  let height = 0;
  const idat = [];

  while (pos < buf.length) {
    const len = buf.readUInt32BE(pos);
    const type = buf.toString("ascii", pos + 4, pos + 8);
    const data = buf.subarray(pos + 8, pos + 8 + len);
    if (type === "IHDR") {
      width = data.readUInt32BE(0);
      height = data.readUInt32BE(4);
      if (data[8] !== 8 || data[9] !== 6) throw new Error("expected 8-bit RGBA");
    } else if (type === "IDAT") idat.push(data);
    else if (type === "IEND") break;
    pos += 12 + len;
  }

  const raw = inflateSync(Buffer.concat(idat));
  const bpp = 4;
  const stride = width * bpp;
  const pixels = Buffer.alloc(height * stride);
  let prev = Buffer.alloc(stride);
  let i = 0;

  for (let y = 0; y < height; y++) {
    const filter = raw[i++];
    const line = Buffer.from(raw.subarray(i, i + stride));
    i += stride;
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? line[x - bpp] : 0;
      const b = prev[x];
      const c = x >= bpp ? prev[x - bpp] : 0;
      if (filter === 1) line[x] = (line[x] + a) & 255;
      else if (filter === 2) line[x] = (line[x] + b) & 255;
      else if (filter === 3) line[x] = (line[x] + ((a + b) >> 1)) & 255;
      else if (filter === 4) {
        const p = a + b - c;
        const pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
        line[x] = (line[x] + (pa <= pb && pa <= pc ? a : pb <= pc ? b : c)) & 255;
      }
    }
    line.copy(pixels, y * stride);
    prev = line;
  }

  return { width, height, pixels };
}

/** Merges runs of set pixels into rectangles, growing them downward where identical. */
function traceMask(mask, width, height) {
  const runs = [];
  for (let y = 0; y < height; y++) {
    let x = 0;
    while (x < width) {
      if (!mask[y * width + x]) { x++; continue; }
      let end = x;
      while (end + 1 < width && mask[y * width + end + 1]) end++;
      runs.push({ y, x, w: end - x + 1, h: 1 });
      x = end + 1;
    }
  }

  // Merge vertically adjacent runs with the same span into taller rectangles.
  const byKey = new Map();
  const rects = [];
  for (const r of runs) {
    const key = `${r.x}:${r.w}`;
    const open = byKey.get(key);
    if (open && open.y + open.h === r.y) open.h += 1;
    else {
      const rect = { ...r };
      rects.push(rect);
      byKey.set(key, rect);
    }
  }

  return rects
    .map((r) => `M${r.x} ${r.y}h${r.w}v${r.h}h-${r.w}z`)
    .join("");
}

const { width, height, pixels } = decodePng(readFileSync(src));
const orange = new Uint8Array(width * height);
const neutral = new Uint8Array(width * height);

for (let y = 0; y < height; y++) {
  for (let x = 0; x < width; x++) {
    const o = (y * width + x) * 4;
    const [r, g, b, a] = [pixels[o], pixels[o + 1], pixels[o + 2], pixels[o + 3]];
    if (a < 128) continue;
    // The mark uses one warm colour and one neutral; split on saturation.
    if (r > g + 40 && r > b + 40) orange[y * width + x] = 1;
    else neutral[y * width + x] = 1;
  }
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" fill-rule="evenodd" shape-rendering="crispEdges">
<path class="dg-mark" fill="currentColor" d="${traceMask(neutral, width, height)}"/>
<path class="dg-accent" fill="#ff5a3c" d="${traceMask(orange, width, height)}"/>
</svg>`;

writeFileSync(out, svg);

// Also emit a React component. An external SVG file cannot read the page's CSS custom
// properties, so inlining it is what lets the neutral half follow the theme and the
// warm half use the brand token rather than a baked-in hex.
const neutralPath = traceMask(neutral, width, height);
const accentPath = traceMask(orange, width, height);

writeFileSync(
  component,
  `// GENERATED by scripts/trace-logo.mjs from public/logo.png — do not edit by hand.
// Traced so the wordmark can be themed: the neutral half takes currentColor and the
// warm half the brand token, instead of shipping fixed-colour raster artwork.

export function LogoMark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 ${width} ${height}"
      role="img"
      aria-label="DotGrey Digital"
      fillRule="evenodd"
      shapeRendering="crispEdges"
      className={className}
    >
      <path fill="currentColor" d="${neutralPath}" />
      <path fill="var(--accent)" d="${accentPath}" />
    </svg>
  );
}
`,
);

console.log(`Wrote ${out} (${(svg.length / 1024).toFixed(1)} KB) and ${component}`);
